### ISSUE TITLE
Sharing Payment

### ISSUE THREAD

**Issue by giuanbalina** [pietrodn/se2-mytaxiservice#14]
The method used to compute the fee is not correct, because it can be applied only at the end of the course, but the passengers get out from the taxi before the end of the ride.

**Comment by giuanbalina** [comment]
The system has to compute the percentage at every destination proportionally with the number of travellers. When a passenger gets out, the system has to compute a percentage that is the weight sum of the previous percentage.

It's quite complex to explain, should I write it in the rasd??

**Comment by pietrodn** [comment]
Well, the passengers enter in advance their destinations, so the computation can be performed even at the beginning of the ride. I was wrong in saying that the computation is done ad the end.

I think that my formulation is slightly clearer, as I specified here: https://github.com/pietrodn/se2-mytaxiservice/blob/master/rasd/specific_requirements/features/ride_sharing.tex
