### ISSUE TITLE
Reasoning for 98% availability

### ISSUE THREAD

**Issue by pietrodn** [pietrodn/se2-mytaxiservice#26]
The reason for not having 99.999% availability or so is that we don't have accounted for replication. Add this in "other design decisions".

**Comment by eleKit** [comment]
We  also need to add this to traceability, in order to link with RASD requirement

**Comment by pietrodn** [comment]
Done in "other design decisions", in https://github.com/pietrodn/se2-mytaxiservice/commit/de634e941aa69f1e41d0af7bc1e5018bfd7d2ebc .
Please add it to traceability.
