### ISSUE TITLE
Reasoning for security

### ISSUE THREAD

**Issue by eleKit** [pietrodn/se2-mytaxiservice#27]
Taken from 3.4.3 Security in RASD:
3. Users’ passwords must not be stored in plain text in the database: instead, they must be hashed and salted.

It needs to be added in DD

**Comment by pietrodn** [comment]
Done in https://github.com/pietrodn/se2-mytaxiservice/commit/de634e941aa69f1e41d0af7bc1e5018bfd7d2ebc
