### ISSUE TITLE
Taxi GPS: is it the GPS of the mobile of the taxi driver, or a separate device?

### ISSUE THREAD

**Issue by pietrodn** [pietrodn/se2-mytaxiservice#6]

**Comment by giuanbalina** [comment]
I think it is better to use the GPS of the mobile phone, because when the taxi driver is available he is in the car or near it, otherwise he can not reach in time the location. In that way it is not necessary a GPS device on the car

**Comment by pietrodn** [comment]
Ok, I asked it because it's not clear what the "GPS of the taxi" means. I think that "GPS of the mobile phone of the taxi driver" is more clear. :)

**Comment by giuanbalina** [comment]
We can also use both for controlling that the taxi driver is in the car

**Comment by pietrodn** [comment]
It's quite hard to control an external GPS remotely, let's just assume that the taxi driver is in the car when he's marked as available.

**Comment by giuanbalina** [comment]
It's the better solution.

**Comment by pietrodn** [comment]
It's clear now.
